# Generated by Django 5.2.5 on 2026-05-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, default='Curated', max_length=50),
        ),
    ]
