# Generated by Django 5.2.5 on 2026-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_badge_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revolut_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
